# Generated by Django 4.1.4 on 2023-01-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create',
            field=models.DateTimeField(),
        ),
    ]
